CREATE  TABLE beenbumped.Users (
	userId INT UNSIGNED NOT NULL AUTO_INCREMENT ,
	personId INT NULL,
	userName VARCHAR(100) NOT NULL,
	password VARCHAR(45) NOT NULL ,
 PRIMARY KEY (userId) ,
 UNIQUE INDEX userId_UNIQUE (userId ASC) ,
 UNIQUE INDEX personId_UNIQUE (personId ASC));