DROP TABLE IF EXISTS beenbumped.Persons;
CREATE TABLE IF NOT EXISTS beenbumped.Persons (
	personId INT UNSIGNED NOT NULL AUTO_INCREMENT ,
	email VARCHAR(320) NOT NULL ,
	firstName VARCHAR(30) NOT NULL ,
	lastName VARCHAR(30) NOT NULL ,
	city VARCHAR(30) NULL ,
	streetName VARCHAR(50) NULL ,
	houseNumber SMALLINT NULL ,
	addressDetails VARCHAR(64) NULL ,
	zipcode INT NULL ,
	phone1 VARCHAR(20) NULL ,
	phone2 VARCHAR(20) NULL ,
	insuranceCompany VARCHAR(64) NULL ,
	insuranceAgentName VARCHAR(64) NULL ,
	insurancePhone1 VARCHAR(20) NULL ,
	insurancePhone2 VARCHAR(20) NULL ,
	insuranceNumber VARCHAR(20) NULL ,
	created DATETIME NOT NULL ,
	modified DATETIME NOT NULL ,
 PRIMARY KEY (personId) ,
 UNIQUE INDEX personId_UNIQUE (personId ASC));